# Generated by Django 3.2.9 on 2022-07-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Music Tittle')),
                ('date', models.DateField(verbose_name='Created Date')),
                ('tag', models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Romance', 'Romance'), ('Jazz', 'Jazz'), ('Rock', 'Rock'), ('Traditional', 'Traditional'), ('Sad', 'Sad')], max_length=200, verbose_name='Enter Keyword')),
                ('image', models.FileField(upload_to='', verbose_name='Upload Your Image')),
                ('Total_min', models.FloatField(verbose_name='Total Time for ur Music')),
                ('desc', models.CharField(max_length=250, verbose_name='description')),
                ('audio', models.FileField(upload_to='audio/', verbose_name='Upload ur Audio')),
                ('video_link', models.CharField(blank=True, max_length=150, verbose_name='Yt Video Link')),
            ],
        ),
        migrations.CreateModel(
            name='Latest_Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.home')),
                ('Episode_2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.home')),
            ],
        ),
    ]
