# Generated by Django 3.2.9 on 2022-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Edit Title')),
                ('Image', models.ImageField(upload_to='', verbose_name='Update Background Image')),
                ('quots', models.CharField(max_length=250, verbose_name='Update Quots')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Update Author')),
            ],
        ),
    ]
