# Generated by Django 3.2.9 on 2022-07-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_episode',
            name='Episode_1',
        ),
        migrations.RemoveField(
            model_name='latest_episode',
            name='Episode_2',
        ),
        migrations.AddField(
            model_name='latest_episode',
            name='Episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='main.home'),
            preserve_default=False,
        ),
    ]
