# Generated by Django 3.2.9 on 2022-07-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220721_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_episode',
            name='Episode',
        ),
        migrations.AddField(
            model_name='latest_episode',
            name='Episode_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epi_1', to='main.home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latest_episode',
            name='Episode_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epi_2', to='main.home'),
        ),
    ]
