# Generated by Django 3.2.9 on 2022-08-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220721_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.FloatField(default=10, max_length=20, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('INR', 'Rs'), ('USD', '$'), ('BTC', 'btc'), ('TRX', 'tron')], default='INR', max_length=5, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(default='you name', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
