# Generated by Django 4.1.2 on 2022-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220817_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('paypal', models.CharField(max_length=100, verbose_name='Paypal')),
                ('upi', models.CharField(max_length=100, verbose_name='UPI')),
                ('qr', models.ImageField(upload_to='', verbose_name='QR')),
            ],
        ),
    ]
